### ISSUE TITLE
How to use with CUDA 9?

### ISSUE THREAD

**Issue by kolkov** [gorgonia/cu#17]
Hi! I use Visual Studio 2017 and CUDA 8.0 can't install with this version.
How to use with CUDA 9.0 RC?

**Comment by chewxy** [comment]
I'm sorry I don't quite follow. Let me try to see if I understand you:
you're on Windows, using Visual Studio... And you can't use the package
with CUDA 8. Is CUDA 8 installed?

**Comment by chewxy** [comment]
I'll work on CUDA 9 soon... right now this supports CUDA 8 only

**Comment by kolkov** [comment]
Have you watched already, are there many differences in the new version, except for the version number? Thanks!

**Comment by chewxy** [comment]
I read the pre-release notes a few weeks ago. I've not looked into it
in-depth because I don't quite have the bandwidth right now

*Xuanyi Chew*
*@chewxy on Twitter*
*Read:* my blog <http://blog.chewxy.com>
*+61403928398*

**Comment by kolkov** [comment]
Yes, I work in Windows. I can not install CUDA 8 by a standard way. The installer fails with new version of Visual Studio. ((

**Comment by kolkov** [comment]
I found an instruction how to install CUDA 8 with Visual Stubio 2017! Thanks!
https://www.olegtarasov.me/how-to-build-cuda-toolkit-projects-in-visual-studio-2017/

**Comment by kolkov** [comment]
CUDA 9 released now.
https://developer.nvidia.com/cuda-toolkit/whatsnew

**Comment by kolkov** [comment]
I tryed to use CUDA 9 and got this error:
```
# github.com/chewxy/cu
C:/Program Files/mingw-w64/x86_64-5.2.0-posix-seh-rt_v4-rev0/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lcuda
collect2.exe: error: ld returned 1 exit status
```

**Comment by chewxy** [comment]
It works now :)
